name: Express deploy digital ocean ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
      - run: |
          npm install
          pm2 delete 0
          pm2 start npm --name "myWebsite" -- run start
          pm2 save
